"""Add reservations and relations

Revision ID: 351cc975fc0b
Revises: 142c59fd4f9f
Create Date: 2026-04-10 16:43:58.764731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '351cc975fc0b'
down_revision: Union[str, Sequence[str], None] = '142c59fd4f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.drop_column('equipment', 'condition')
    op.add_column('memberships', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.alter_column('memberships', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('memberships_user_id_key'), 'memberships', type_='unique')
    op.drop_column('memberships', 'valid_until')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_admin')
    op.add_column('memberships', sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('memberships_user_id_key'), 'memberships', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('memberships', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('memberships', 'start_date')
    op.add_column('equipment', sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
