"""fix reservation model field

Revision ID: 7e5cf27c6afb
Revises: 73b7799508ee
Create Date: 2026-04-11 23:24:18.805005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5cf27c6afb'
down_revision: Union[str, Sequence[str], None] = '73b7799508ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('equipment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('reservations_training_id_fkey'), type_='foreignkey')
        batch_op.drop_column('training_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('reservations_training_id_fkey'), 'trainings', ['training_id'], ['id'])
        batch_op.alter_column('equipment_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
